---
title: "logic_checks"
author: "HK"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(openxlsx)
source("logic_checks.R")
```


```{r}
file_ds <- "sample_msna_data_cati.xlsx"

main_ds <- read.xlsx(file_ds, sheet = 1)

loop_3 <- read.xlsx(file_ds, sheet = 2)

```


## Conducting formalized logic checks

Helper file for these checks is to be filled in. 

Fields in a helper file (for cross-checks):

- target_var - variable to be checked
- target_val - value of the target variable to be checked
- cross_var - variable to be checked against
- cross_val - value in cross variable to be checked

```{r}
logic_checks <- read.xlsx("MSNA_log_checks.xlsx", sheet = "cross_check_main_ds")


log_ch_main <- get_logic_errors_categorical(data = main_ds, logic_frame = logic_checks, id_col = "_uuid", enum_col = "enum_id", date_col = "date_survey", enum_com_col = "N_1_enumerator_comment_note")

log_ch_loop <- get_logic_errors_categorical(data = loop_3, logic_frame = logic_checks, id_col = "_uuid", index_col = "_index")

```

### Categoical to numeric

```{r}
logic_checks <- read.xlsx("MSNA_log_checks.xlsx", sheet = "num_check_loop3")


get_logic_errors_categorical_numeric  <- function(data, logic_frame, id_col, enum_col="complementary_col", date_col="complementary_col", enum_com_col="complementary_col", index_col="complementary_col"){
  
  data <- data |> mutate(complementary_col = NA_character_)
    
  log_checks_issues_num <- data.frame(matrix(nrow = 0, ncol = 8))
  
  colnames(log_checks_issues_num) <- c(id_col, enum_col, date_col, enum_com_col, "issue", "comment", "variable_to_change", "correct_value") 
  #names(log_checks_issues_num) <- names(log_checks_issues_num)[!duplicated(names(log_checks_issues_num))]
  
  data <- data |> 
    mutate(across(is.logical, as.numeric))

for (i in 1:nrow(logic_checks)){
  var <- logic_checks$target_var[i]
  crvar <- logic_checks$cross_var[i]
  
  val <- logic_checks$target_val[i]
  crval <- logic_checks$cross_val[i]
  
  sign <- logic_checks$sign[i]
  
  `%.%` <- get(sign)
  
  logic_temp <- data |> 
    filter(!!sym(var) == paste0(val) & !!sym(crvar) %.% paste0(crval)) |> 
    select(!!sym(id_col), !!sym(enum_col), !!sym(date_col), !!sym(enum_com_col), !!sym(index_col)) |> 
    mutate(issue = paste0("Inconsistent answers: ", val, " in ", var, " and ", crval, " is ", sign, " ", crvar), comment = NA_character_)

  log_checks_issues_num <- rbind(log_checks_issues_num, logic_temp)
  log_checks_issues_num <- log_checks_issues_num |> 
    select(-contains("complementary_col"))
  }
  return(log_checks_issues_num)
}



log_ch_num <- get_logic_errors_categorical_numeric(data = loop_3, logic_frame = logic_checks, id_col = "relationship_instance", index_col = "_index")

log_ch_num <- log_ch_num |> mutate(ds = "loop3")
#start from here tomorrow
```

```{r}
lc <- plyr::rbind.fill(log_ch, log_ch_num)

write.xlsx(lc, "log_frame_issues.xlsx")
```


### Apply logic check after revision

```{r}
logic_issues_all <- read.xlsx("log_frame_issues.xlsx")
```

```{r}

logic_issues_main <- logic_issues_all |> filter(ds == "main")

get_logic_applied <- function(data, logic_frame_issues, idvar){
  nam_ds <- names(data)
  nam_logic <- logic_frame_issues$variable_to_change
  id_logic <- logic_frame_issues[idvar]
  nam_ds <- setdiff(nam_ds, idvar)


  for(vi in nam_logic){
    id_logic_i <- logic_frame_issues[logic_frame_issues$variable_to_change == vi, idvar]

    for(id in id_logic_i){

    data[which(data[idvar] == id), vi] <- logic_frame_issues$correct_value[which(logic_frame_issues[idvar] == id & logic_frame_issues$variable_to_change == vi)]
   
    }

  }
  return(data)
}


data2 <- get_logic_applied(main_ds, logic_issues_main |> filter(!is.na(variable_to_change)), idvar="_uuid")
```

